### ISSUE TITLE
Order of hashes no longer canonical

### ISSUE THREAD

**Issue by SomberNight** [peterbe/hashin#105]
Since version 0.14, the order of hashes does not seem to be deterministic.
Before 0.14, the hashes used to be lexicographically ordered.

I am guessing this was changed in https://github.com/peterbe/hashin/pull/95

What is the reason for this?

We use hashin in electrum for deterministic builds.
The [requirements files](https://github.com/spesmilo/electrum/blob/c7f3adb67ea6afd50fec60221ba711ddea110281/contrib/deterministic-build/requirements.txt) are generated by [this script](https://github.com/spesmilo/electrum/blob/c7f3adb67ea6afd50fec60221ba711ddea110281/contrib/freeze_packages.sh).
The `freeze_packages.sh` script is manually rerun to update dependencies (see e.g. https://github.com/spesmilo/electrum/commit/ba4af29bf82f7addb68c3ed996002665313ab223).
If the order of hashes for a given package is not canonical, then rerunning the script can result in changes for packages that have not actually been updated, making the diff considerably less readable.

**Comment by peterbe** [comment]
The original issue was: https://github.com/peterbe/hashin/issues/93

The reasoning was that when the code that determines whether to edit the list of hashes kick in, it should be agnostic of order. Because, the order of them does not matter to `pip`. Also, it doesn't really make sense to sort something like that. 

Also, I don't understand why you point out [this commit](https://github.com/spesmilo/electrum/commit/ba4af29bf82f7addb68c3ed996002665313ab223). There's no change of order of hashes there.

**Comment by peterbe** [comment]
By the way, I couldn't help but to notice...

```bash
for requirement in $requirements; do
    echo -e "\r  Hashing $requirement..."
    $other_python -m hashin -r $contrib/deterministic-build/requirements${i}.txt ${requirement}
done
```
Can, in theory, be replaced with:

```bash
echo -e "\r  Hashing $requirements..."
$other_python -m hashin -r $contrib/deterministic-build/requirements${i}.txt ${requirements}
```
Referring [to this](https://github.com/spesmilo/electrum/blob/c7f3adb67ea6afd50fec60221ba711ddea110281/contrib/freeze_packages.sh#L31-L34).

**Comment by mythmon** [comment]
I think that Hashin should take a stronger approach here than "whatever PyPI.org does". Consistency is useful, both for deterministic builds and for smaller, easier to read diffs. I think that sorting the hashes in the file anytime Hashin writes them goes a long way towards that end.

Deterministic build are important because of projects like Debian's [ReproducibleBuilds](https://wiki.debian.org/ReproducibleBuilds), which strive to increase trust and verifiability of packages. These are some of the same goals that hashing packages in Python is intended to solve.

Another tool that is similar to Hashin also uses sorting to help consistency: Yarn. It sorts entries both in `package.json` and also `yarn.lock`. It doesn't ever have lists of hashes, but it sorts dependencies alphabetically when listing them.

**Comment by peterbe** [comment]
@di Do you have an opinion on this one? Should the requirements file that `hashin` builds sort the hashes lexicographically ordered, no matter what, or should it sort them by the same way that PyPI presents them?

I would argue that it's a no-problem because the only time it comes up is if you compare two different requirements files made in two different places when PyPI might have returned files in a different order. E.g. 

```bash
# On machine X
$ hashin Django -r reqs-x.txt
```
```bash
# On machine Y
$ hashin Django -r reqs-y.txt
$ rsync reqs-y.txt machineX:
```
```bash
# On machine X
# This *will* diff if the order of files 
# on https://pypi.org/pypi/Django/json changed over time. 
$ diff reqs-x.txt reqs-y.txt
```

Contrast with doing it all and always on the *same* machine:

```bash
# Monday
$ hashin Django==2.1.5 -r /path/to/reqs.txt
```

```bash
# Tuesday
# This will ONLY diff if the SET of hashes has changed between Monday and Tuesday
$ hashin Django==2.1.5 -r /path/to/reqs.txt --dry-run
```

Essentially, what `hashin` does when it figures out to bother changing the requirements file is this:

```python
if set(hashes_from_parsing_existing_file) != set(hashes_from_pypi_download):
    amend_requiments_file(hashes_from_pypi_download)
```

**Comment by SomberNight** [comment]
> if you compare two different requirements files made in two different places when PyPI might have returned files in a different order

In Electrum's case, the file is not always generated by the same developer. I think it's unrealistic to assume in general that frozen dependency files are always updated from the same machine.

**Comment by di** [comment]
@peterbe Thanks for looping me in.

I would expect the hashes to be sorted lexicographically.

The ordering from PyPI doesn't have much meaning to users: it is ordered by the filename of the distribution artifact. Since `hashin` doesn't include filenames in it's output, this ordering wouldn't make much sense to a user trying to understand why `hashin` insists on it.

**Comment by peterbe** [comment]
I get the feeling that all y'all people are saying that it would be good to NOT rely on the sorting of PyPI and instead always write down the hashes lexicographically sorted. Yes, it has the advantage that the files created a more predictable when compared as a whole. 

I don't think the existing logic that determines whether it should amend the hashes should change but *when it does* it should sort the hashes before writing them.

**Comment by SomberNight** [comment]
Yes I think that's a good solution.
To restate, if the set of hashes already in the file and the new set of hashes are equal, it's okay to leave the file as is (ignore order when comparing, detect as no change);
but if the sets are unequal, what gets written should be lexicographically sorted.

**Comment by peterbe** [comment]
This is now out in [version 0.14.5](https://github.com/peterbe/hashin/commit/23840376aaf09746264a99545526fe4bbec93e17).
